# Generated by Django 4.2.3 on 2023-07-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
